### ISSUE TITLE
Practica_2 web 2.0_Abigail Coronel Santiago

### ISSUE THREAD

**Issue by abicoronel** [SistemasTecTlaxiaco/actividad-5-proceso-de-negocio-en-bizagi-con-web-20-equipo_judith#4]
[Practica de BPMN de modelo de negocios de la web 2_ISC_Abigail Coronel Santiago.pdf](https://github.com/SistemasTecTlaxiaco/actividad-5-proceso-de-negocio-en-bizagi-con-web-20-equipo_judith/files/9649680/Practica.de.BPMN.de.modelo.de.negocios.de.la.web.2_ISC_Abigail.Coronel.Santiago.pdf)

**Comment by EdwinOrtiz1412** [comment]
calificación: 20 %

**Comment by josealfredo79** [comment]
Bien hecho y revisado..
